version: '3.5'
services: 
  mongo:
    container_name: mongo
    image: mongo:${MONGODB_TAG}
    ports: 
      - ${MONGO_EXTERNAL}:${MONGO_INTERNAL}
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - ./mongo/db:/data/db
  flask_app:
    container_name: flask_app
    image: python:${FLASK_APP_TAG}
    ports: 
      - ${FLASK_APP_EXTERNAL}:${FLASK_APP_INTERNAL}
    volumes: 
      - ./flask_app:/flask_app
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: [/flask_app/entrypoint.sh]
networks: 
  neighborhood:
    name: ${DC_NETWORK}
    driver: bridge